-- Local development notes (WS14-T020)
-- Programmatic seeding lives in supabase/seed.ts — run:
--
--   CODECARD_LOCAL_SEED=1 \
--   CODECARD_LOCAL_SEED_PASSWORD='…' \
--   npm run db:seed
--
-- See docs/LOCAL_SEED.md. This SQL file is intentionally not auto-applied with
-- secrets; use the TypeScript seeder so production guards and idempotency run.
--
-- Sample identity (created by seed.ts):
--   email: local.dev@codecard.local.test
--   slug:  local-dev
--   Never seeds production (gclteunkzorwaliwhatp).
--   Never overwrites the staging showcase slug alex-chen.
