import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
        colors: {
        ink: 'var(--ink)',
        canvas: 'var(--canvas)',
        surface: 'var(--surface)',
        carbon: 'var(--carbon)',
        moss: 'var(--moss)',
        fern: 'var(--fern)',
        stone: 'var(--stone)',
        phosphor: 'var(--phosphor)',
        midnight: 'var(--midnight)',
        'deep-indigo': 'var(--deep-indigo)',
        'void-canvas': 'var(--void-canvas)',
        'lilac-white': 'var(--lilac-white)',
        pearl: 'var(--pearl)',
        ash: 'var(--ash)',
        fog: 'var(--fog)',
        steel: 'var(--steel)',
        lichen: 'var(--lichen)',
        graphite: 'var(--graphite)',
        lavender: 'var(--lavender)',
        vellum: 'var(--vellum)',
        obsidian: 'var(--obsidian)',
        smoke: 'var(--smoke)',
        twilight: 'var(--twilight)',
        'graphite-surface': 'var(--graphite-surface)',
        charcoal: 'var(--charcoal)',
        reactor: 'var(--reactor)',
        'reactor-bright': 'var(--reactor-bright)',
        'lavender-mist': 'var(--lavender-mist)',
        bone: 'var(--bone)',
        'slate-veil': 'var(--slate-veil)',
        gunmetal: 'var(--gunmetal)',
        abyss: 'var(--abyss)',
        vault: 'var(--vault)',
        paper: 'var(--paper)',
        lime: 'var(--lime)',
        violet: 'var(--violet)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-on-light': 'var(--text-on-light)',
        border: 'var(--border)',
        accent: 'var(--accent)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--surface)',
        muted: 'var(--text-secondary)',
        cream: 'var(--hume-cream)',
        'lavender-mist-brand': 'var(--hume-lavender-mist)',
        periwinkle: 'var(--hume-periwinkle)',
        'chart-hume': 'var(--chart-hume)',
        'chart-compare': 'var(--chart-compare)',
        'surface-dark': 'var(--surface-dark)',
        'line-soft': 'var(--line-soft)',
      },
      maxWidth: {
        container: '1280px',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'Georgia', 'ui-serif', 'serif'],
        eyebrow: ['var(--font-eyebrow)', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        nav: '100px',
        card: '10px',
        btn: '100px',
        link: '8px',
        badge: '100px',
      },
      boxShadow: {
        rim: 'inset 0 0 0 1px rgba(228, 217, 255, 0.06)',
        'rim-strong': 'inset 0 0 0 1px rgba(228, 217, 255, 0.1)',
      },
    },
  },
  plugins: [],
} satisfies Config;
