import { createElement } from 'react';
import type { IconType } from 'react-icons';
import { FaAws, FaDatabase, FaTerminal } from 'react-icons/fa6';
import {
  SiAndroid,
  SiAngular,
  SiAnthropic,
  SiApacheairflow,
  SiApachecassandra,
  SiApachehadoop,
  SiApachekafka,
  SiApachespark,
  SiApple,
  SiArgo,
  SiAstro,
  SiBun,
  SiC,
  SiCplusplus,
  SiClickhouse,
  SiCloudflare,
  SiCss,
  SiCypress,
  SiDatabricks,
  SiDatadog,
  SiDeno,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElasticsearch,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGatsby,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGo,
  SiGooglecloud,
  SiGooglegemini,
  SiGrafana,
  SiGraphql,
  SiHelm,
  SiHono,
  SiHtml5,
  SiHuggingface,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiKotlin,
  SiKubernetes,
  SiLangchain,
  SiLaravel,
  SiLinear,
  SiLinux,
  SiMeta,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNewrelic,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNotion,
  SiNpm,
  SiNx,
  SiOpenai,
  SiOpencv,
  SiOpenjdk,
  SiOpentelemetry,
  SiPhp,
  SiPlanetscale,
  SiPnpm,
  SiPostgresql,
  SiPrisma,
  SiPrometheus,
  SiPytorch,
  SiPython,
  SiQwik,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRemix,
  SiRubyonrails,
  SiRuby,
  SiRust,
  SiSass,
  SiSentry,
  SiSharp,
  SiSlack,
  SiSnowflake,
  SiSocketdotio,
  SiSolid,
  SiSpring,
  SiSpringboot,
  SiSqlite,
  SiStorybook,
  SiStripe,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTurborepo,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiWebpack,
  SiYarn,
  SiYolo,
} from 'react-icons/si';

/** Sliced-window mark for SAHI, which has no brand icon in the icon set. */
const SahiIcon: IconType = (props) =>
  createElement(
    'svg',
    {
      viewBox: '0 0 24 24',
      fill: 'currentColor',
      xmlns: 'http://www.w3.org/2000/svg',
      ...props,
    },
    createElement('path', {
      d: 'M3 3h7.2v7.2H3V3zm10.8 0H21v7.2h-7.2V3zM3 13.8h7.2V21H3v-7.2zm10.8 0H21V21h-7.2v-7.2z',
    }),
  );

const TECH_MAP: Record<string, IconType> = {
  android: SiAndroid,
  angular: SiAngular,
  apachekafka: SiApachekafka,
  kafka: SiApachekafka,
  apple: SiApple,
  ios: SiApple,
  argo: SiArgo,
  aws: FaAws,
  bun: SiBun,
  c: SiC,
  'c++': SiCplusplus,
  cplusplus: SiCplusplus,
  cpp: SiCplusplus,
  'c#': SiSharp,
  csharp: SiSharp,
  clickhouse: SiClickhouse,
  cli: FaTerminal,
  terminal: FaTerminal,
  cloudflare: SiCloudflare,
  css: SiCss,
  css3: SiCss,
  deno: SiDeno,
  docker: SiDocker,
  dotnet: SiDotnet,
  '.net': SiDotnet,
  elasticsearch: SiElasticsearch,
  elastic: SiElasticsearch,
  expo: SiExpo,
  fastapi: SiFastapi,
  firebase: SiFirebase,
  flutter: SiFlutter,
  gatsby: SiGatsby,
  gcp: SiGooglecloud,
  'google cloud': SiGooglecloud,
  git: SiGit,
  github: SiGithub,
  'github actions': SiGithubactions,
  githubactions: SiGithubactions,
  gitlab: SiGitlab,
  go: SiGo,
  golang: SiGo,
  grafana: SiGrafana,
  graphql: SiGraphql,
  grpc: SiSocketdotio,
  helm: SiHelm,
  html: SiHtml5,
  html5: SiHtml5,
  javascript: SiJavascript,
  js: SiJavascript,
  jenkins: SiJenkins,
  kotlin: SiKotlin,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  linux: SiLinux,
  mongodb: SiMongodb,
  mongo: SiMongodb,
  mysql: SiMysql,
  nestjs: SiNestjs,
  'nest.js': SiNestjs,
  nextjs: SiNextdotjs,
  'next.js': SiNextdotjs,
  nginx: SiNginx,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  'node.js': SiNodedotjs,
  npm: SiNpm,
  openai: SiOpenai,
  opentelemetry: SiOpentelemetry,
  otel: SiOpentelemetry,
  php: SiPhp,
  planetscale: SiPlanetscale,
  pnpm: SiPnpm,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  prisma: SiPrisma,
  prometheus: SiPrometheus,
  python: SiPython,
  pytorch: SiPytorch,
  react: SiReact,
  reactjs: SiReact,
  'react.js': SiReact,
  redis: SiRedis,
  ruby: SiRuby,
  rust: SiRust,
  sass: SiSass,
  scss: SiSass,
  sentry: SiSentry,
  slack: SiSlack,
  sqlite: SiSqlite,
  stripe: SiStripe,
  supabase: SiSupabase,
  svelte: SiSvelte,
  swift: SiSwift,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  'tailwind css': SiTailwindcss,
  tensorflow: SiTensorflow,
  terraform: SiTerraform,
  typescript: SiTypescript,
  ts: SiTypescript,
  vercel: SiVercel,
  vite: SiVite,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  'vue.js': SiVuedotjs,
  webpack: SiWebpack,
  websocket: SiSocketdotio,
  websockets: SiSocketdotio,
  yarn: SiYarn,
  java: SiOpenjdk,
  openjdk: SiOpenjdk,
  jdk: SiOpenjdk,
  spring: SiSpring,
  springboot: SiSpringboot,
  'spring boot': SiSpringboot,
  opencv: SiOpencv,
  'open cv': SiOpencv,
  yolo: SiYolo,
  yolo11: SiYolo,
  yolov5: SiYolo,
  yolov8: SiYolo,
  yolov11: SiYolo,
  ultralytics: SiYolo,
  sahi: SahiIcon,
  sam: SiMeta,
  sam2: SiMeta,
  sam3: SiMeta,
  'segment anything': SiMeta,
  gemini: SiGooglegemini,
  googlegemini: SiGooglegemini,
  sql: FaDatabase,
  socketio: SiSocketdotio,
  'socket.io': SiSocketdotio,
  rabbitmq: SiRabbitmq,
  cassandra: SiApachecassandra,
  snowflake: SiSnowflake,
  databricks: SiDatabricks,
  airflow: SiApacheairflow,
  spark: SiApachespark,
  hadoop: SiApachehadoop,
  flask: SiFlask,
  django: SiDjango,
  rails: SiRubyonrails,
  'ruby on rails': SiRubyonrails,
  laravel: SiLaravel,
  express: SiExpress,
  'express.js': SiExpress,
  expressjs: SiExpress,
  hono: SiHono,
  remix: SiRemix,
  astro: SiAstro,
  solid: SiSolid,
  solidjs: SiSolid,
  'solid.js': SiSolid,
  qwik: SiQwik,
  turborepo: SiTurborepo,
  nx: SiNx,
  jest: SiJest,
  vitest: SiVitest,
  cypress: SiCypress,
  storybook: SiStorybook,
  figma: SiFigma,
  notion: SiNotion,
  linear: SiLinear,
  datadog: SiDatadog,
  newrelic: SiNewrelic,
  'new relic': SiNewrelic,
  huggingface: SiHuggingface,
  'hugging face': SiHuggingface,
  langchain: SiLangchain,
  llm: SiOpenai,
  llms: SiOpenai,
  anthropic: SiAnthropic,
  claude: SiAnthropic,
  'ci/cd': SiGithubactions,
  cicd: SiGithubactions,
  devops: SiDocker,
  'machine learning': SiPytorch,
  ml: SiPytorch,
  'ai/ml': SiPytorch,
  ai: SiOpenai,
  'artificial intelligence': SiOpenai,
  observability: SiGrafana,
  databases: SiPostgresql,
  database: FaDatabase,
  'amazon web services': FaAws,
  'computer vision': SiOpencv,
  cv: SiOpencv,
};

function normalizeTechKey(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, ' ');
}

export function getTechLabel(name: string): string {
  return name.trim();
}

export function resolveTechIcon(name: string): IconType | null {
  const key = normalizeTechKey(name);
  if (TECH_MAP[key]) return TECH_MAP[key];
  const collapsed = key.replace(/[\s._-]+/g, '');
  return TECH_MAP[collapsed] ?? null;
}

export function techIconAbbreviation(name: string): string {
  const label = getTechLabel(name);
  const parts = label.split(/[\s./-]+/).filter(Boolean);
  if (parts.length >= 2) {
    return parts
      .slice(0, 2)
      .map((p) => p[0])
      .join('')
      .toUpperCase();
  }
  return label.slice(0, 3).toUpperCase();
}
