import type { IconType } from 'react-icons';
import { FaAws, FaTerminal } from 'react-icons/fa6';
import {
  SiAndroid,
  SiAngular,
  SiApachekafka,
  SiApple,
  SiArgo,
  SiBun,
  SiC,
  SiCplusplus,
  SiClickhouse,
  SiCloudflare,
  SiCss,
  SiDeno,
  SiDocker,
  SiDotnet,
  SiElasticsearch,
  SiExpo,
  SiFastapi,
  SiFirebase,
  SiFlutter,
  SiGatsby,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGo,
  SiGooglecloud,
  SiGrafana,
  SiGraphql,
  SiHelm,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiKotlin,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNpm,
  SiOpenai,
  SiOpentelemetry,
  SiPhp,
  SiPlanetscale,
  SiPnpm,
  SiPostgresql,
  SiPrisma,
  SiPrometheus,
  SiPytorch,
  SiPython,
  SiReact,
  SiRedis,
  SiRuby,
  SiRust,
  SiSass,
  SiSentry,
  SiSharp,
  SiSlack,
  SiSqlite,
  SiStripe,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVuedotjs,
  SiWebpack,
  SiYarn,
} from 'react-icons/si';

/** Lavender icon tint for Simple Icons CDN fallback */
const SIMPLE_ICON_COLOR = 'c4a7ff';

const TECH_MAP: Record<string, IconType> = {
  android: SiAndroid,
  angular: SiAngular,
  apachekafka: SiApachekafka,
  kafka: SiApachekafka,
  apple: SiApple,
  ios: SiApple,
  argo: SiArgo,
  aws: FaAws,
  bun: SiBun,
  c: SiC,
  'c++': SiCplusplus,
  cplusplus: SiCplusplus,
  cpp: SiCplusplus,
  'c#': SiSharp,
  csharp: SiSharp,
  clickhouse: SiClickhouse,
  cli: FaTerminal,
  terminal: FaTerminal,
  cloudflare: SiCloudflare,
  css: SiCss,
  css3: SiCss,
  deno: SiDeno,
  docker: SiDocker,
  dotnet: SiDotnet,
  '.net': SiDotnet,
  elasticsearch: SiElasticsearch,
  elastic: SiElasticsearch,
  expo: SiExpo,
  fastapi: SiFastapi,
  firebase: SiFirebase,
  flutter: SiFlutter,
  gatsby: SiGatsby,
  gcp: SiGooglecloud,
  'google cloud': SiGooglecloud,
  git: SiGit,
  github: SiGithub,
  'github actions': SiGithubactions,
  githubactions: SiGithubactions,
  gitlab: SiGitlab,
  go: SiGo,
  golang: SiGo,
  grafana: SiGrafana,
  graphql: SiGraphql,
  grpc: SiGooglecloud,
  helm: SiHelm,
  html: SiHtml5,
  html5: SiHtml5,
  javascript: SiJavascript,
  js: SiJavascript,
  jenkins: SiJenkins,
  kotlin: SiKotlin,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  linux: SiLinux,
  mongodb: SiMongodb,
  mongo: SiMongodb,
  mysql: SiMysql,
  nestjs: SiNestjs,
  'nest.js': SiNestjs,
  nextjs: SiNextdotjs,
  'next.js': SiNextdotjs,
  nginx: SiNginx,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  'node.js': SiNodedotjs,
  npm: SiNpm,
  openai: SiOpenai,
  opentelemetry: SiOpentelemetry,
  otel: SiOpentelemetry,
  php: SiPhp,
  planetscale: SiPlanetscale,
  pnpm: SiPnpm,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  prisma: SiPrisma,
  prometheus: SiPrometheus,
  python: SiPython,
  pytorch: SiPytorch,
  react: SiReact,
  reactjs: SiReact,
  'react.js': SiReact,
  redis: SiRedis,
  ruby: SiRuby,
  rust: SiRust,
  sass: SiSass,
  scss: SiSass,
  sentry: SiSentry,
  slack: SiSlack,
  sqlite: SiSqlite,
  stripe: SiStripe,
  supabase: SiSupabase,
  svelte: SiSvelte,
  swift: SiSwift,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  tensorflow: SiTensorflow,
  terraform: SiTerraform,
  typescript: SiTypescript,
  ts: SiTypescript,
  vercel: SiVercel,
  vite: SiVite,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  'vue.js': SiVuedotjs,
  webpack: SiWebpack,
  websockets: SiReact,
  yarn: SiYarn,
};

/** Simple Icons slugs when react-icons has no match (cdn.simpleicons.org) */
const SIMPLE_ICON_SLUG: Record<string, string> = {
  protobuf: 'protobuf',
  socketio: 'socketdotio',
  'socket.io': 'socketdotio',
  websocket: 'socketdotio',
  websockets: 'socketdotio',
  rabbitmq: 'rabbitmq',
  cassandra: 'apachecassandra',
  dynamodb: 'amazondynamodb',
  snowflake: 'snowflake',
  databricks: 'databricks',
  airflow: 'apacheairflow',
  spark: 'apachespark',
  hadoop: 'apachehadoop',
  flask: 'flask',
  django: 'django',
  rails: 'rubyonrails',
  'ruby on rails': 'rubyonrails',
  laravel: 'laravel',
  spring: 'spring',
  'spring boot': 'springboot',
  express: 'express',
  'express.js': 'express',
  hono: 'hono',
  remix: 'remix',
  astro: 'astro',
  solidjs: 'solid',
  'solid.js': 'solid',
  qwik: 'qwik',
  turborepo: 'turborepo',
  nx: 'nx',
  jest: 'jest',
  vitest: 'vitest',
  playwright: 'playwright',
  cypress: 'cypress',
  storybook: 'storybook',
  figma: 'figma',
  notion: 'notion',
  linear: 'linear',
  datadog: 'datadog',
  newrelic: 'newrelic',
  huggingface: 'huggingface',
  'hugging face': 'huggingface',
  langchain: 'langchain',
  llm: 'openai',
  llms: 'openai',
  openai: 'openai',
  anthropic: 'anthropic',
  claude: 'anthropic',
  gemini: 'googlegemini',
  'ci/cd': 'githubactions',
  cicd: 'githubactions',
  devops: 'docker',
  'machine learning': 'pytorch',
  ml: 'pytorch',
  ai: 'openai',
  'artificial intelligence': 'openai',
  observability: 'grafana',
  databases: 'postgresql',
  'amazon web services': 'amazonwebservices',
};

function normalizeTechKey(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, ' ');
}

export function getTechLabel(name: string): string {
  return name.trim();
}

export function resolveTechIcon(name: string): IconType | null {
  const key = normalizeTechKey(name);
  return TECH_MAP[key] ?? null;
}

export function resolveSimpleIconUrl(name: string): string | null {
  const key = normalizeTechKey(name);
  if (resolveTechIcon(name)) return null;

  const slug = SIMPLE_ICON_SLUG[key];
  if (!slug) return null;

  return `https://cdn.simpleicons.org/${slug}/${SIMPLE_ICON_COLOR}`;
}

export function techIconAbbreviation(name: string): string {
  const label = getTechLabel(name);
  const parts = label.split(/[\s./-]+/).filter(Boolean);
  if (parts.length >= 2) {
    return parts
      .slice(0, 2)
      .map((p) => p[0])
      .join('')
      .toUpperCase();
  }
  return label.slice(0, 3).toUpperCase();
}
