-- Force RLS even for table owners (defense in depth)
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_memberships FORCE ROW LEVEL SECURITY;
ALTER TABLE profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE profile_links FORCE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
ALTER TABLE project_domains FORCE ROW LEVEL SECURITY;
ALTER TABLE project_focus_areas FORCE ROW LEVEL SECURITY;
ALTER TABLE project_media_assets FORCE ROW LEVEL SECURITY;
ALTER TABLE project_links FORCE ROW LEVEL SECURITY;
ALTER TABLE project_orderings FORCE ROW LEVEL SECURITY;
ALTER TABLE saved_connections FORCE ROW LEVEL SECURITY;
ALTER TABLE connection_notes FORCE ROW LEVEL SECURITY;
ALTER TABLE collections FORCE ROW LEVEL SECURITY;
ALTER TABLE collection_items FORCE ROW LEVEL SECURITY;
ALTER TABLE public_profile_events FORCE ROW LEVEL SECURITY;
ALTER TABLE project_view_events FORCE ROW LEVEL SECURITY;
ALTER TABLE subscription_customers FORCE ROW LEVEL SECURITY;
ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_events FORCE ROW LEVEL SECURITY;
ALTER TABLE moderation_reports FORCE ROW LEVEL SECURITY;
ALTER TABLE dmca_notices FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE jobs FORCE ROW LEVEL SECURITY;

-- Revoke default public access; API uses authenticated roles with policies
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO anon;
